version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade awscli
      - mvn test
      - mvn clean package
      - aws cloudformation package --template DeployLambdaPipe-template.yml --s3-bucket $S3_BUCKET --output-template DeployLambdaPipe-template-export.yml
artifacts: 
  type: zip
  files:
    - DeployLambdaPipe-template-export.yml
