version: 0.2

env:
  variables:
    CFN_TEMPLATE_FILE: "JavaSpringApiLambdaChangeset.yml"
    COMPILED_CODE_LOCATION: "target/java-api-REST-lambda-*.jar" 

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade awscli
      - mvn test
      - mvn clean package
      - aws cloudformation package --template JavaSpringApiLambdaChangeset.yml --s3-bucket $S3_BUCKET --output-template JavaSpringApiLambdaChangeU.yml
artifacts: 
  files:
    - JavaSpringApiLambdaChangeU.yml
