version: 0.2

env:
  variables:
    CFN_TEMPLATE_FILE: "JavaSpringApiLambdaChangeset.yml"
    COMPILED_CODE_LOCATION: "target/java-api-REST-lambda-*.jar" 

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade awscli
      - mvn test
      - mvn clean package

  post_build:
    commands:
      - echo S3_BUCKET = $S3_BUCKET
      - pip install --upgrade awscli
      - mv target/java-api-REST-lambda-*.jar .
      - rm -rf target src buildspec.yml pom.xml
      - aws cloudformation package --template JavaSpringApiLambdaChangeset.yml --s3-bucket $S3_BUCKET --output-template JavaSpringApiLambdaChangesetToapply.yml

artifacts: 
  files:
    - JavaSpringApiLambdaChangesetToapply.yml
    - java-api-REST-lambda-*.jar
