version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade awscli
      - mvn test
      - mvn clean package
      - echo S3_BUCKET = $S3_BUCKET
      - aws cloudformation package --template JavaSpringApiLambdaChangeset.yml --s3-bucket $S3_BUCKET --output-template JavaSpringApiLambdaChangesetExport.yml
artifacts: 
  files:
    - JavaSpringApiLambdaChangesetExport.yml
