version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade awscli
      - mvn test
      - mvn clean package
      - echo S3_BUCKET=$S3_BUCKET
      - echo S3_NAME=$S3_NAME
      - rm target/original-*
      - COMPILED_JAR="$(ls target/*.jar | xargs -n 1 basename)"
      - sed -i "s/S3_BUCKET/$S3_BUCKET/g" JavaSpringApiLambdaChangeset.yml
      - sed -i "s/S3_NAME/$S3_NAME/g" JavaSpringApiLambdaChangeset.yml
      - sed -i "s/COMPILED_JAR/$COMPILED_JAR/g" JavaSpringApiLambdaChangeset.yml
artifacts: 
  files:
    - JavaSpringApiLambdaChangeset.yml
    - *.jar
