version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade awscli
      - mvn test
      - mvn clean package
      - rm -rf target src buildspec.yml pom.xml
      - aws cloudformation package --template JavaSpringApiLambdaChangeset.yml --s3-bucket $S3_BUCKET --output-template JavaSpringApiLambdaChangesetExport.yml
artifacts: 
  files:
    - target/java-api-REST-lambda-0.*.jar
