version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade awscli
      - mvn test
      - mvn clean package
      - COMPILED_JAR="$(ls target/*.jar | xargs -n 1 basename)"
      - FORMAT_S3_TARGET=${TARGET_S3_BUCKET_AND_SUBFOLDERS//\//\\/}
      - sed -i "s/TARGET_S3_BUCKET_AND_SUBFOLDERS/$FORMAT_S3_TARGET/g" JavaSpringApiLambdaChangesetNew.yml
      - sed -i "s/COMPILED_JAR/$COMPILED_JAR/g" JavaSpringApiLambdaChangesetNew.yml
artifacts: 
  files:
    - JavaSpringApiLambdaChangeset.yml
    - java-api-REST-lambda-0.*.jar
