version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - pip install --upgrade awscli
      - mvn test
      - mvn clean package
      - aws cloudformation package --template JavaSpringApiLambdaChangeset.yml --s3-bucket $S3_BUCKET --output-template JavaSpringApiLambda-export.yml
artifacts: 
  files:
    - JavaSpringApiLambda-export.yml
