AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  JavaSpringApiLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: s3://S3_BUCKET/S3_NAME/target/COMPILED_JAR
      Handler: hello.handler.javaApiRESTLambdaHandler::myTestHandler
      Runtime: java8
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post

