TemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  JavaSpringApiLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: hello.handler.javaApiRESTLambdaHandler::myTestHandler
      Runtime: java8
      AutoPublishAlias: live2
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: post

